### ISSUE TITLE
Allow forgetting the cached data for uploaded package.json

### ISSUE THREAD

**Issue by stof** [npmgraph/npmgraph#118]
When selecting a package.json file, the name+version will probably not change when you edit locally (as the file probably does not have a meaningful version anyway if it is not a published package). As the npmgraph tool uses sessionStorage as the cache, it currently ignores any change I do in my package.json when I reupload, unless I close my browser or I manually delete the cache through the dev tools.

![image](https://user-images.githubusercontent.com/439401/148582053-b954e7ce-c446-4d8b-8e41-8e3feb6bb371.png)

Maybe the best solution would be that a new selected file always replaces the cache. But otherwise, I would be fine with at least a button to delete a cached file from this "recent files" list.

**Comment by broofa** [comment]
Good catch.  It's worth noting that this is only a problem if the `version` field is a) specified,  and b) doesn't change.  If `version` is omitted, we just use the current timestamp, which will change on each upload.  Still... I agree the latest upload should take precedence.

**Comment by stof** [comment]
oh, I was not aware that I could omit the `version` field in my package.json. I have `0.0.0` in it since years, because that's what gets generated (or at least used to) by the `init` command.
