### ISSUE TITLE
Unreadable text in dark mode with "Colorize by" options

### ISSUE THREAD

**Issue by neodon** [npmgraph/npmgraph#137]
I'm using dark mode and selected one of the "Colorize by" options. This leaves the text as white on very light backgrounds for the graph nodes, which is unreadable.

<img width="820" alt="image" src="https://github.com/npmgraph/npmgraph/assets/82944/b45c50f8-01c6-4517-87a5-50d582226b22">

**Comment by broofa** [comment]
Fixed (finally!)
<img width="971" alt="image" src="https://github.com/npmgraph/npmgraph/assets/164050/95069edf-f240-4f10-968e-7bb9bc696c09">
