### ISSUE TITLE
Display outdated / latest versions

### ISSUE THREAD

**Issue by jimmywarting** [npmgraph/npmgraph#138]
It would be interesting to find out which packages are in need of being updated.

**Comment by jimmywarting** [comment]
thinking it would kind of work like how vscode shows latest version when hovering a dependency in package.json

![image](https://github.com/npmgraph/npmgraph/assets/1148376/72ca1288-6f71-4aa5-87a1-9c5f26b8e488)

**Comment by jimmywarting** [comment]
I know! 
how about a dropdown where you could select the version you which to view?

kind of like jsdeliver 

<img width="844" alt="image" src="https://github.com/npmgraph/npmgraph/assets/1148376/9ac2eff3-1dfe-4918-afc0-dc14f7e551a0">

but with clear indication if it's the newest version

**Comment by jimmywarting** [comment]
ofc it would also be useful to know which packages who are deprecated as well.

they could be represented as:

<img width="544" alt="image" src="https://github.com/npmgraph/npmgraph/assets/1148376/cf99f9e0-adc1-4ded-ae4c-93e36de29a7d">

**Comment by jimmywarting** [comment]
When you hover over a a module maybe a simple title could be enough:

<img width="261" alt="image" src="https://github.com/npmgraph/npmgraph/assets/1148376/a7438b92-145d-4874-8ab7-7b30765327b7">

**Comment by jimmywarting** [comment]
just spitballing ideas...

**Comment by broofa** [comment]
Hmm... I'm thinking the simplest approach might be to do a colorize-by-outdated-status.  'Could use red for major-outdated modules, orange for minor-outdated modules, and yellow for patch-outdated modules.

Shouldn't be that hard to implement if you want to take stab at it.  Have a look at what I'm doing for colorize-by-module-type:
[Colorizing logic](https://github.com/npmgraph/npmgraph/blob/main/components/GraphDiagram/GraphDiagram.tsx#L321-L340)

And references to `COLORIZE_MODULE_TYPE` in https://github.com/npmgraph/npmgraph/blob/main/components/GraphPane/GraphPane.tsx for the UI.

(There should really be a "`Colorizor`" interface of some sort to make it easier to write colorizors in one place.)

**Comment by jimmywarting** [comment]
👍 

could also break this down to multiple smaller issues:

- [ ] Colorize graph items by outdated version status
- [ ] Add title attribute to graph items that tells you what the latest version is.
- [ ] Create a dropdown list to select which version you want to have a look at (in the sidebar)
