### ISSUE TITLE
Feat: Ability to Expand and Collapse each node

### ISSUE THREAD

**Issue by prabodhmeshram** [npmgraph/npmgraph#139]
### Problem:

Given the overwhelming graph that gets rendered even for a small dependency package.json file, its is really hard to kind of visualise the package peer dependencies relationship in the UI. There is no way we can see a graph for a single node.

### Proposed Solution:

Ability for each node to collapse or expand on clicking would greatly simplify the UX. It can even zero down the overwhelming UI to top dependency listed as per package.json rather rendering all dependency at once in full expanded mode.

**Comment by broofa** [comment]
You can shift-click modules in the graph to expand / collapse them.

![CleanShot 2023-08-22 at 09 58 00](https://github.com/npmgraph/npmgraph/assets/164050/ca13b326-2675-419c-881c-3bbdea567813)
