### ISSUE TITLE
Feat: Ability to Highlight the Author when a package a dependency is selected

### ISSUE THREAD

**Issue by prabodhmeshram** [npmgraph/npmgraph#140]
### Problem:

Right now when we select a node module in the UI on the right side panel, it highlights the tree selection on the left graph, which is great. But there is no highlight on the author(s) of the package.

### Solution

When we select a node module, we should also highlight the contributor(s) in the right pane.

**Comment by broofa** [comment]
It already does this.  When you select a module on the graph, it shows the module information - including the maintainers - in the inspector:
![CleanShot 2023-08-22 at 09 51 14](https://github.com/npmgraph/npmgraph/assets/164050/713d4c06-cb4b-4e54-b7ab-aeb76330bd53)

What am I missing?

**Comment by broofa** [comment]
No response.  Closing.
