### ISSUE TITLE
Handle `npm:` aliases in dependencies

### ISSUE THREAD

**Issue by broofa** [npmgraph/npmgraph#143]
For example [in this graph](https://npmgraph.js.org/?q=%40isaacs%2Fcliui)
![CleanShot 2023-08-26 at 10 41 19@2x](https://github.com/npmgraph/npmgraph/assets/164050/187ee5cc-edfc-4826-9b44-5c06fdb50a84)

**Comment by broofa** [comment]
Fixed.

**Comment by fabiospampinato** [comment]
I don't know if it's related, now `npm:` aliases are resolved, but when I click on any package or any maintainer on the sidebar the entire graph disappears

**Comment by broofa** [comment]
@fabiospampinato It's working for me.  Can you open a new issue with the following:
* The specific URL you're on
* The browser and OS
* Any errors or logs in the console
* And just for good-measure, a whole-window screenshot might be helpful

**Comment by broofa** [comment]
Reopening, as this appears to have regressed. 😕
