### ISSUE TITLE
Support for loading a package.json file from query parameters

### ISSUE THREAD

**Issue by fabiospampinato** [npmgraph/npmgraph#145]
I'm using a little [tool](https://github.com/fabiospampinato/banal) for generating bundle analyses with esbuild, but without the graph from `npmgraph` it doesn't quite tell me the whole story, but opening the website and manually telling it what to show a graph for is not as convenient as writing 2 words in the terminal.

Would it be possible to add support for loading a `package.json` file encoded directly in the query parameters? With that I could automate my workflow a bit, and speed things up.

**Comment by broofa** [comment]
What about just enumerating your package.json#dependences in the `q` param?  E.g. https://npmgraph.js.org/?q=sshpk,smpp,ansiterm (... and so on)

**Comment by fabiospampinato** [comment]
I could! I didn't know that was possible 😃 thanks!

**Comment by broofa** [comment]
Not quite what you're after, but you can know provide a URL instead of module name.  So you could conceivably serve the package JSON files locally and point to that.  (Requires CORS, though.)

**Comment by broofa** [comment]
See also https://github.com/npmgraph/npmgraph/issues/94

**Comment by broofa** [comment]
Hey @fabiospampinato , you should be able to open a package.json by simply opening a URL with the package.json contents in the URL `hash`.  See the new [URL API](https://github.com/npmgraph/npmgraph/#url-api) for details.
