### ISSUE TITLE
BundlePhobia site no longer reliable

### ISSUE THREAD

**Issue by broofa** [npmgraph/npmgraph#146]
It's been down for a couple weeks now (at least), and the project owner is unresponsive.
* Near term: Remove "Bundle Size"  from Module pane UI
* Longer term: Figure out an alternative for this

See https://github.com/pastelsky/bundlephobia/issues/823

**Comment by styfle** [comment]
You could switch to showing Install Size instead (although might not be relevant for browser packages)

https://github.com/styfle/packagephobia
