### ISSUE TITLE
Clicking maintainer resets graph

### ISSUE THREAD

**Issue by broofa** [npmgraph/npmgraph#152]
First reported in #143 by @fabiospampinato.

I just happened to reproduce this while testing out Chrome's new "Recorder" feature (Developer Tools -> Recorder).  [Here's the recording](https://gist.github.com/broofa/fec981ef6b869296c93457c1dc8d8dc4).

**Comment by broofa** [comment]
@fabiospampinato:  This should be fixed now.  Please try again.  If it's still a problem, let me know and I'll reopen.

**Comment by fabiospampinato** [comment]
Now it works, thanks 👍
