### ISSUE TITLE
Input field style

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#160]
Can you restore this border style on the field? 

<img width="229" alt="Screenshot 2" src="https://github.com/npmgraph/npmgraph/assets/1402241/255e34dd-aae3-4c4c-9047-3cbb80dc81d7">

This is what it looks like currently in Safari (it's the default "3D inset" `border-style`)

<img width="428" alt="Screenshot 1" src="https://github.com/npmgraph/npmgraph/assets/1402241/629f9645-cc2b-462e-a506-728d1430feae">

Without the search icon it's ok. Also it looks like there's extra margin on the left

_Originally posted by @fregante in https://github.com/npmgraph/npmgraph/issues/156#issuecomment-1741720275_

**Comment by fregante** [comment]
Sorry I should have just opened an issue instead 😁

**Comment by broofa** [comment]
No worries.  I just dropped this into the current PR [here](https://github.com/npmgraph/npmgraph/pull/157/commits/1fb3dccd0e678470d57f6a06fcf44d72305e804b).
