### ISSUE TITLE
496 Modules in <summary> only 453 <div class="title"> elements on page

### ISSUE THREAD

**Issue by guest271314** [npmgraph/npmgraph#185]

**Comment by guest271314** [comment]
Would be helpful if the full list were exportable as an array serialized to JSON.

**Comment by broofa** [comment]
What URL are you seeing this issue on?

**Comment by guest271314** [comment]
https://github.com/GoogleChromeLabs/telnet-client/blob/main/package.json.

I got 514 with this

```
let nodePackageDependencies = [
  ...new Set(
    Object.entries(
      (await (await fetch(
        "./package-lock.json",
      )).json()).packages,
    ).map((
      [key, { dependencies = {}, devDependencies = {} }],
    ) => [
      key.replace(/^node_modules\//, ""),
      ...Object.keys(dependencies),
      ...Object.keys(devDependencies),
    ]).flat().filter(Boolean),
  ),
];

console.log(nodePackageDependencies, nodePackageDependencies.length);
```

![Dependencies_for_telnet_client_0_0_1_dependencies](https://github.com/npmgraph/npmgraph/assets/4174848/42b254d5-2281-4293-808c-112b3e31aaa8)

**Comment by guest271314** [comment]
![Screenshot_2023-11-26_12-20-35](https://github.com/npmgraph/npmgraph/assets/4174848/b3f59987-ae66-4493-8fdd-953d0001bb92)

**Comment by broofa** [comment]
Oh, I see what's happening.  The modules `<summar>` in the Graph Pane lists module *names*, not versions, but a module may appear in the graph multiple times under different versions.    E.g. `commander` appears four times (v2.20.3, v4.1.1, v7.2.0, and v8.3.0) in the graph, but is only appears once in the summary as "commander (4)".

**Comment by guest271314** [comment]
So what is the correct answer?

**Comment by broofa** [comment]
"496"

**Comment by broofa** [comment]
... at least for the github.com...package.json link.  It looks like the published version of `telnet-client` only has 454 modules: https://npmgraph.js.org/?q=telnet-client#deps=devDependencies

**Comment by guest271314** [comment]
Not sure that settles the matter https://gist.github.com/jimmywarting/327a647942014d8ac4f4a333c351f94c?permalink_comment_id=4773369#gistcomment-4773369

> - telnet requires express.
> - the hook kind of redirect and says: require express@2.x instead!
> telnet require express@2.x
> - express@2.x says it needs to require cookie-parser
> - the "hook" figures out that it's express@2.x who wants to load cookie-parser so it should say: require cookie-parser@4.3
> -and so on...

**Comment by guest271314** [comment]
> but a module may appear in the graph multiple times under different versions. E.g. commander appears four times (v2.20.3, v4.1.1, v7.2.0, and v8.3.0) in the graph, but is only appears once in the summary as "commander (4)".

I think those versions need to appear in the summaries for completeness https://gist.github.com/jimmywarting/327a647942014d8ac4f4a333c351f94c?permalink_comment_id=4773369#gistcomment-4773369

> one huge blocker i might see is how would you resolve dependency that use different version?
> 
> ```
> - express@2.0
>   - cookie-parser@4.3
> - session@5.2
>   - cookie-parser@3.11
> ```
> the express dependency might need / depend on cookie-parser@4.x and session need cookie-parser@3.x

**Comment by guest271314** [comment]
Thanks for looking into this either way.

**Comment by guest271314** [comment]
Best explanation I've read yet https://www.reddit.com/r/node/comments/184hkw1/comment/kaxn88r/:

> Because 1) Throwing away a package-lock.json and re-resolving/-installing everything can give a different result, and 2) package-lock.json stores the hoisted node_modules tree, not just resolved packages.
> 
> Take ajv as an example.
> 
> The package-lock.json contains 5 versions of it (6.12.6, 8.8.2, 8.10.0, 8.11.0, 8.11.2) but resolving again from the package.json now will give you 2 versions (6.12.6, 8.12.0), which is what npmgraph.js.org counts.
> 
> Also, your code actually counts ajv 6 times
> 
> ajv
> ajv-formats/node_modules/ajv
> copy-webpack-plugin/node_modules/ajv
> mini-css-extract-plugin/node_modules/ajv
> webpack-dev-middleware/node_modules/ajv
> webpack-dev-server/node_modules/ajv
> Because ajv-formats/node_modules/ajv and webpack-dev-server/node_modules/ajv are the exact same package (ajv@8.8.2) that appears twice in the filesystem. **In the general case, it is not possible to perfectly dedupe packages in a node_modules tree.**
> 
>> I'm curious what you get using npm and/or yarn
> 
> For yarn v4 I got 542 packages. One of the reasons is that it treats node-gyp as an explicit dependency while npm treats it as implicit.
> 
> Didn't test with npm but they should match the two numbers you got depending on whether you use the lockfile or not

(Emphasis added)

**Comment by broofa** [comment]
> I think those versions need to appear in the summaries for completeness https://gist.github.com/jimmywarting/327a647942014d8ac4f4a333c351f94c?permalink_comment_id=4773369#gistcomment-4773369

You're gonna have to elaborate on how that gistcomment relates to this conversation.  Not sure I understand.

FWIW, I'm about to push a new version of the UI that lists each `name@version` tuple separately.  See https://github.com/npmgraph/npmgraph/pull/186 ("All modules" section)

> Throwing away a package-lock.json and re-resolving/-installing everything can give a different result

Sure.  Package lock files are basically a snapshot of a given-project's dependency tree.  The exact content of a package.json file is a product of the order and timing in which modules are installed for any given project.

While lock files and package.json files are similar in some ways, they're different enough that supporting them is non-trivial.  See also #148

**Comment by guest271314** [comment]
> You're gonna have to elaborate on how that gistcomment relates to this conversation. Not sure I understand.

What I am doing is elimination use of `npm` altogether. 

Somebody claimed here [Can this be used to create/download npm as a standalone executable? #3237](https://github.com/nvm-sh/nvm/issues/3237).

> npm can’t be eliminated from the equation when you’re dealing with JavaScript

So I am vetting that claim. Since I have a GitHub repository locally that I have already built using `npm`, then deleted the `node_modules`, I am starting there https://github.com/guest271314/telnet-client/tree/user-defined-tcpsocket-controller-web-api.

I narrowed down the only modules I think I need for what I'm doing (full-duplex streaming between an arbitrary Web page and the `TCPSocket` in an Isolated Web App and to the TCP server, local or remote) I only need

- wbn
- webn-sign
- rollup-plugin-webbundle

and the dependencies those scripts depend on.

I went full bore with the `package-lock.json` file, because, in general, I only download the `node` executable, along with the other JavaScript runtime executables I continually test and experiment with, Deno, Bun, QuickJS, txiki.js, et al. In my opnion Node.js is more of a proprietary system compared to default Ecmascript Modules implementation outside of the archaic Node.js `node_modules`, CommonJS, and `package.json`, system; when comparing modern JavaScript runtimes. More packages, yes, comparable to other JavaScript runtimes process of importing scripts, no.

> FWIW, I'm about to push a new version of the UI that lists each name@version tuple separately. See https://github.com/npmgraph/npmgraph/pull/186 ("All modules" section)

Looks good to a point. Missing a JSON export. The SVG graph is useless to me except for showing you what happened. The `.json` file is actionable.

> Sure. Package lock files are basically a snapshot of a given-project's dependency tree. The exact content of a package.json file is a product of the order and timing in which modules are installed for any given project.

That's Node.js-specific infrastructure. I don't even store a `package.json` nor `nodule_modules` file on my machine. I stpre the `node` executable in local `~/bin` file, set in `PATH` and go, adjacent to the rest of the JavaScript engines and runtime executables I test, e.g., `js`, `d8`, `bun`, etc.

> While lock files and package.json files are similar in some ways, they're different enough that supporting them is non-trivial. See also https://github.com/npmgraph/npmgraph/issues/148

That's all rather insane to me. It shouldn't be this difficult (https://github.com/jsdelivr/jsdelivr/issues/18542) to just fetch, or bundle scripts to work in Ecmascript Module environment, or when there is no `npm` or `nodule_modules` on the system. In my opinion.

**Comment by guest271314** [comment]
Looks like `bun install` installs packages listed in `package.json` to `~/.bun/install/cache`. Don't know if `npm` is built in to `bun` under the hood, yet. I know I didn't call `npm install` because `npm` ain't on my system.

Now I just need to figure out how to call the equivalent of `npm run build` for

```
  "scripts": {
    "start": "webpack serve --config webpack.dev.js",
    "build": "webpack --config webpack.wbn.js",
    "lint": "eslint src/*.ts"
  }
```

**Comment by guest271314** [comment]
Figured it out. `bun run build`. Didn't work when the `package-lock.json` file was in the repository. Thanks, again!

```
$ bun install
bun install v1.0.14 (d8be3e51)
error: Please upgrade package-lock.json to lockfileVersion 3

Run 'npm i --lockfile-version 3 --frozen-lockfile' to upgrade your lockfile without changing dependencies.
user@user:~/telnet-client-web-ext$ bun install
bun install v1.0.14 (d8be3e51)
 + @typescript-eslint/eslint-plugin@5.62.0 (v6.13.0 available)
 + @typescript-eslint/parser@5.62.0 (v6.13.0 available)
 + clean-webpack-plugin@4.0.0
 + copy-webpack-plugin@11.0.0
 + css-loader@6.8.1
 + dotenv@16.3.1
 + eslint@8.54.0
 + eslint-config-google@0.14.0
 + gh-pages@4.0.0 (v6.1.0 available)
 + html-loader@3.1.2 (v4.2.0 available)
 + html-webpack-plugin@5.5.3
 + mini-css-extract-plugin@2.7.6
 + style-loader@3.3.3
 + ts-loader@9.5.1
 + typescript@4.9.5 (v5.3.2 available)
 + wbn-sign@0.1.0 (v0.1.2 available)
 + webbundle-webpack-plugin@0.1.3
 + webpack@5.89.0
 + webpack-cli@4.10.0 (v5.1.4 available)
 + webpack-dev-server@4.15.1
 + webpack-merge@5.10.0
 + xterm@4.19.0 (v5.3.0 available)
 + xterm-addon-fit@0.5.0 (v0.8.0 available)

 494 packages installed [5.67s]
user@user:~/telnet-client-web-ext$ bun run build
$ webpack --config webpack.wbn.js
Setting the empty headerOverrides to IWA defaults. To bundle a non-IWA, set `integrityBlockSign { isIwa: false }` in your plugin configs. Defaults are set to:
 {"content-security-policy":"base-uri 'none'; default-src 'self'; object-src 'none'; frame-src 'self' https: blob: data:; connect-src 'self' https:; script-src 'self' 'wasm-unsafe-eval'; img-src 'self' https: blob: data:; media-src 'self' https: blob: data:; font-src 'self' blob: data:; require-trusted-types-for 'script'; frame-ancestors 'self';","cross-origin-embedder-policy":"require-corp","cross-origin-opener-policy":"same-origin","cross-origin-resource-policy":"same-origin"}
assets by path *.js 4.34 KiB
  asset main.js 3.05 KiB [emitted] [minimized] (name: main)
  asset runtime.js 910 bytes [emitted] [minimized] (name: runtime)
  asset sw.js 361 bytes [emitted] [from: assets/sw.js] [copied] [minimized]
  asset worker.js 50 bytes [emitted] [from: assets/worker.js] [copied] [minimized]
assets by path images/ 21.2 KiB
  asset images/icons-512.png 14.2 KiB [emitted] [from: assets/images/icons-512.png] [copied]
  asset images/icons-192.png 5.14 KiB [emitted] [from: assets/images/icons-192.png] [copied]
  asset images/icons-vector.svg 1.89 KiB [emitted] [from: assets/images/icons-vector.svg] [copied]
asset telnet.swbn 32.6 KiB [emitted]
asset manifest.webmanifest 721 bytes [emitted] [from: assets/manifest.webmanifest] [copied]
asset index.html 253 bytes [emitted]
Entrypoint main 3.94 KiB = runtime.js 910 bytes main.js 3.05 KiB
runtime modules 2.48 KiB 3 modules
./src/index.js 4.74 KiB [built] [code generated]

LOG from webbundle-webpack-plugin
<i> isolated-app://<ID>/

webpack 5.89.0 compiled successfully in 1500 ms
user@user:~/telnet-client-web-ext$ npm --help
Command 'npm' not found, but can be installed with:
sudo apt install npm
```
