### ISSUE TITLE
Use `package` (query param array) instead of `packages` (JSON field), and support nameless packages

### ISSUE THREAD

**Issue by broofa** [npmgraph/npmgraph#195]
Per #193, we should be able to improve the utility / form of the existing `packages` field.  Specifically:
* Don't require packages to be named
* Take advantage of `URLSearchParams` support for multiple param values

I think the sub-tasks here are as follows...
* [ ] Provide each uploaded/manually-provided package as a separate `package` query param
* [ ] Treat `name`-less packages as top-level entry points
* [ ] Deprecate the `packages` param

Open issues:
* [ ] How should name-less packages be displayed in the graph / UI?  Currently the just appear as "Unnamed package", but that gets confusing if there's more than one name-less package.
* [ ] If a `package` has a name, should it be a top-level entry point by default (like name-less packages)?  As noted in 193, the current setup is that `packages` have to be explicitly mentioned in the `q` param for them to be top-level.  Failing that, they'll only appar in the graph if referenced as a dependency by another module.

**Comment by fregante** [comment]
> * [ ]  Provide each uploaded/manually-provided package as a separate `package` query param


I think:

```diff
- new URLSearchParams([['packages', JSON.stringify([pkg1, pkg2])]])
+ new URLSearchParams([pkg1, pkg2].map(pkg => ['package', pkg]))
```



> * [ ]  Treat `name`-less packages as top-level entry points

If you go all the way with my suggestion, you can use the first provided package as the entry point, rather than depend on whether they have a name. But I might have misunderstood this point.




> * How should name-less packages be displayed in the graph / UI?  Currently the just appear as "Unnamed package"

"uploaded"? "Unnamed package" is fine too

> but that gets confusing if there's more than one name-less package

If they're all unnamed, you can call them Giorgio, Giovanni, Paolo, Mario, … heheh I mean if they're unnamed then you can't name them 😅 




> * if a `package` has a name, should it be a top-level entry point by default (like name-less packages)?

Same as as above, `packages[0]`

**Comment by fregante** [comment]
> Use package (query param array) 

Not worth it anymore, you'll have to keep supporting the array anyway. As long as that's well documented it's not a big deal.

I opened a dedicate issue for the name:

- #260
