### ISSUE TITLE
Free-form text field users for exracting dependencies from package.json content (full or partial), or other sources of dependencies

### ISSUE THREAD

**Issue by broofa** [npmgraph/npmgraph#196]
In addition to the existing options for specifying packages / dependencies (`q` param names, file upload, `q` param urls), it would be convenient to have a way generating graphs from ... 
  * [ ] package.json contents (copy/pasted) #97
  * [ ] package.json `dependencies`-like fragments (e.g. copy/pasting just the inner or outer portions of `dependencies`)
  * [ ] package-lock.json or `yarn.lock` ala #148 (file sizes make these problematic?)
  * [ ] top-of-file `import` statements
  
[Gist with examples of the above](https://gist.github.com/broofa/f0a154d7b58a0cdea9c267c07d80e395)

'Not really sure what this looks like in the UI.  I'm inclined to just keep it simple (e.g. `<textarea>`) as opposed to diving down the rabbit-hole of rich text editors.

**Comment by fregante** [comment]
I think you don't really need a field for this, you just need to accept and capture the paste event, either in the current field or just anywhere on the page. 

Adding another field for this seems unnecessary, you really just want to paste content, not provide an editor for tweaking—rather, that could be a whole separate tab/feature, but it's not needed nor useful for pasting. 

If you see the feature this way, you really only need two small pieces of code:

- instructions on the Start tab
- a `paste` event handler that calls the same function the file input calls

A total of +6 lines of code to implement package.json pastes:

- #97

**Comment by fregante** [comment]
Regarding fragment parsing:

- not sure if you want to venture into parsing of invalid syntax
- whatever is pasted/parsed can just be first turned into a valid package.json internally

Related issue for nameless packages:

- #97

**Comment by fregante** [comment]
I'm going to close this as too broad if you don't mind. 🥹 As follow-up issues I suggest:

- [ ] Extract `imports` from JS text/files (regardless of paste, drop, `input[file]` select)
- [ ] Support package.json `dependencies`-like fragments  (not a fan, honestly, people can just paste the whole package.json)
- [ ] Add way to _add_ packages to the graph 

_Removing_ packages is already supported via shift-click. Adding packages would be possible via custom input mode (cmd-enter in the current search field, for example). That just about covers most such usages and be more useful in general.

The free-form editor could be an advanced input mode, but I think it would be a bit excessive for npmgraph. Best to open an issue _just_ for such a field (without mentioning additional parse types)
