### ISSUE TITLE
Move `q` URL Parameter to hash parameters

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#198]
What's the logic between adding parameters to the hash? Is it to avoid sending unnecessary data to the server?

For simplicity, I think it would be easier to move the `q` parameter to the hash as well

```diff
- https://npmgraph.js.org/?q=send#deps=devDependencies
+ https://npmgraph.js.org/#q=send&deps=devDependencies
```

Or, if you're not afraid of the extra traffic, just use regular search parameters for all

```diff
- https://npmgraph.js.org/?q=send#deps=devDependencies
+ https://npmgraph.js.org/?q=send&deps=devDependencies
```

**Comment by broofa** [comment]
While I suppose we could just stick everything in the hash, something about that feels wrong.  It means the server (such as it is) never knows what graph is being rendered.

At the moment the potential change I see here is to move `deps` from the hash to the search params.

**Comment by fregante** [comment]
> the server (such as it is) never knows what graph is being rendered.

Why is that a problem? Isn't this a full SPA? The server always serves the same HTML page, right?

**Comment by broofa** [comment]
[much-delayed reply]  For the record, having `q` in query params is useful for analytics.
