### ISSUE TITLE
TypeError in /

### ISSUE THREAD

**Issue by broofa** [npmgraph/npmgraph#199]
## Error in NPMGraph

**TypeError** in **/**
AbortSignal?.timeout is not a function

[View on Bugsnag](https://app.bugsnag.com/bit-above-software-llc/npmgraph/errors/658edc35541d2b0008797e62?event_id=658edc8100cf4970cfe90000&i=gh&m=ci)

## Stacktrace

    lib/fetchJSON.ts:26 - nj
    components/ModulePane/ModuleBundleSize.tsx:25 - null

[View full stacktrace](https://app.bugsnag.com/bit-above-software-llc/npmgraph/errors/658edc35541d2b0008797e62?event_id=658edc8100cf4970cfe90000&i=gh&m=ci)

*Created by Robert Kieffer via Bugsnag*

**Comment by preethamrn** [comment]
Hi, I'm using a modern browser (Firefox 121.0) and this error started showing up. I visited https://npmgraph.js.org/ a few days ago without any issues.

I think the error may be linked to the `hasExpectedFeatures` method which was recently added. https://github.com/npmgraph/npmgraph/commit/e805323be842ea042839c95e167d0f52c5b6f9a4#diff-98aa886d94b42299b459b9a47d2715fd00aff6e9155157f269518d19f99689c4R19

Seems like it always returns false and therefore will always render unsupported.

**Comment by preethamrn** [comment]
Created a pull request for your convenience. Let me know if it looks good or if my fix is wrong. I'll admit I'm not completely familiar with the entire codebase. https://github.com/npmgraph/npmgraph/pull/201

**Comment by broofa** [comment]
Good catch.  Sorry about that.  I've merged your PR and it should be working again.

Classic case of rushing a new feature because "What could possibly be wrong with it!" 🙄
