### ISSUE TITLE
Unable to see graph in private registry

### ISSUE THREAD

**Issue by EmmetBeachBum** [npmgraph/npmgraph#204]
Apologies in advance if this is not the right place or way to do this - this is my first time writing down an issue.

I am trying to use npmgraph to see dependencies inside my private scoped registry (running using Verdaccio).
I installed the local version of npmgraph and edited its `config.js` file to point at my registry instead of npmjs.

I am able to connect to my localhost just fine and see the server's website. However, whenever I put any package's name into the search bar and hit the 'show' button, nothing happens.
I tried checking the log file under AppData/Local/npm-cache/_logs, but there was nothing indicative - no error I could spot, nor any log to indicate that my search was registered at all by the server.

Am I doing something wrong? Did I miss a step? I would appreciate anyone's help. Thank you.

**Comment by broofa** [comment]
Duplicate of https://github.com/npmgraph/npmgraph/issues/19
