### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#205]
What's a "release" in npmgraph? Every commit is immediately published, I don’t think it's useful to version/tag any particular commit.

**Comment by broofa** [comment]
Having a semver is semi-useful for tracking regressions in BugSnag.  Also for communicating changes to the URL API.  And maybe at some point for keeping the web app and CLI in sync.

All of that said, I haven't been particularly rigorous or consistent in how/when I bump the semver.  🤷
