### ISSUE TITLE
Consistently support caret (^) ranges

### ISSUE THREAD

**Issue by fabiospampinato** [npmgraph/npmgraph#207]
It looks like when dragging a `package.json` into the website then dependencies like this are picked up correctly: `"vscode-extras": "^1.8.0"`, but if I manually input `vscode-extras^1.8.0` into the website then it can't understand it anymore, which seems inconsistent.

**Comment by fregante** [comment]
`vscode-extras^1.8.0` is invalid, `vscode-extras@^1.8.0` works

https://npmgraph.js.org/?q=vscode-extras%40%5E1.8.0
