### ISSUE TITLE
Switch/Toggle is backwards

### ISSUE THREAD

**Issue by styfle** [npmgraph/npmgraph#217]
### npmgraph
<img width="312" alt="npmgraph" src="https://github.com/npmgraph/npmgraph/assets/229881/8b468056-2108-4fac-ab51-5715eac60e14"/>

### iOS
<img width="312" alt="ios" src="https://github.com/npmgraph/npmgraph/assets/229881/38f22e51-8d5f-4541-b9aa-4a07d2e965c4" />

### Android

<img width="312" alt="android" src="https://github.com/npmgraph/npmgraph/assets/229881/34dcbe21-846b-4412-a673-4ff09b4635b0"/>

**Comment by broofa** [comment]
<img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaWU2MHlmbnRtc3pnMnptbTIwYWxkdjZqcnRkYWp0dnM3MWg3ZncxYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3ofSBnfTFad2KLT464/giphy.gif" width="300" />

**Comment by styfle** [comment]
Thanks for the quick fix! 🚀
