### ISSUE TITLE
Restore npm.broofa.com redirect

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#221]
I mentioned the tool quite a bit in the past and all those links are now dead, e.g. in https://github.com/mozilla/addons-linter/pull/3600

It would be good to keep a redirect on that domain.

**Comment by styfle** [comment]
Should be a couple clicks with the Vercel dashboard. 

https://vercel.com/docs/projects/domains/deploying-and-redirecting

**Comment by fregante** [comment]
broofa.com has nameservers set to Dreamhost

**Comment by styfle** [comment]
You can use CNAME for the subdomain, right?

**Comment by fregante** [comment]
CNAME only masks it, you need an actual redirect. I don't know if Dreamhost offers that, otherwise I generally use http://redirect.center which allows it via DNS

**Comment by broofa** [comment]
Should be working now (or soon-ish, once DNS change propagates).

Probably-obvious disclaimer:  broofa.com is my personal site so, yeah, links to anything there are "at your own risk".  I don't have concrete plans to break it or hand ownership off to someone else, but there's definitely a "bus factor" in play.  Or more like "57-year old guy who just got back into mountain biking"-factor. 😁

**Comment by fregante** [comment]
Yeah no worries, it's more of an issue with existing links.

By the way it's not working due to lack of HTTPS support 😬 

https://npm.broofa.com/?q=image-size

**Comment by fregante** [comment]
I think the DNS has propagated, but the website is not set up correctly. This is what it looks like after bypassing the HTTPS warning

<img width="597" alt="Screenshot 21" src="https://github.com/user-attachments/assets/68eb52a7-c0d5-4dc0-a119-a7b8f3929f9a">

**Comment by broofa** [comment]
Looks like dreamhost doesn't support subdomain redirects for HTTPS 😢 .  Giving redirect.center a go, but I'm not entirely sure I have the CNAME entry setup properly.    (It's a little unclear how the options for forwarding the uri path and https are handled are specified.  Trying `npmgraph.js.org.opts-uri.opts-https.redirect.center` to see if that works ...)

**Comment by broofa** [comment]
Hmm.  Looks like redirect.center can do HTTP -> HTTPS redirects, but not HTTPS -> HTTPS.

**Comment by broofa** [comment]
Ah, I think I've got it figured.  Looks like domain-forward.com does both HTTP and HTTPS redirects.  Please test and let me know if there's any issues.

**Comment by styfle** [comment]
I think there was some confusion about my suggestion above, so let me elaborate. 

You can keep your nameservers as-is and add a new CNAME record like so:

```
npm.broofa.com.	300	IN	CNAME	cname.vercel-dns.com.
```

Then you can add `npm.broofa.com` as a project domain in the Vercel dashboard by visiting:

```
https://vercel.com/<team>/<project>/settings/domains
```

Finally, you configure it to redirect from one project domain to the other domain. In this case, you would select `npm.broofa.com` and redirect it to `npmgraph.js.org` and choose 307 as temporary or 308 as permanent redirect depending on how you want to do it.

**Comment by fregante** [comment]
It worked!

**Comment by fregante** [comment]
That domain appears to be hacked, you might want to use a different one

https://github.com/user-attachments/assets/4bf71df3-b779-4e01-bd57-f704a3b798bc

**Comment by broofa** [comment]
> That domain appears to be hacked

Ugh... okay, trying @styfle's suggestion (as I probably should have from the start).

**Comment by broofa** [comment]
@fregante vercel CNAME seems to be working.   Try again, please?

**Comment by fregante** [comment]
It loads the website under the domain, but it should be a redirect or else you'll see your domain popup in search, etc. This is what I meant in https://github.com/npmgraph/npmgraph/issues/221#issuecomment-2226921945

<img width="850" alt="Screenshot 1" src="https://github.com/user-attachments/assets/44d7811c-8569-4b84-afa9-4b20b6aa1397">

**Comment by broofa** [comment]
### ThIs TiMe FoR sUrE!

(It helps if you enable redirects in Vercel domain settings)

(@styfle I can feel your eyeroll all the way over here. Stop judging me, damnit!)

**Comment by fregante** [comment]
<img width="164" alt="Screenshot" src="https://github.com/user-attachments/assets/dd8788e6-4ccf-4f71-8135-b758dae2a58d">

**Comment by styfle** [comment]
Glad you got it working 😃
