### ISSUE TITLE
Graph not centered on `select`ed item on first load

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#233]
_Originally posted by @broofa in https://github.com/npmgraph/npmgraph/issues/229#issuecomment-2226908197_

Something's not working right here (still).  If I select the `env-paths` modules [in this graph](https://npmgraph-git-scroll-on-safari-broofas-projects.vercel.app/?q=npm#select=exact%3Aenv-paths%402.2.1), it center the view on `env-paths` as expected:

<img src="https://github.com/user-attachments/assets/b51d0cfc-4dec-4d9c-9bb1-88dd73cc62a5" width="300" />

... but if I then reload the page, it doesn't even come close to it:
<img src="https://github.com/user-attachments/assets/329fcbdc-8ea1-4504-94e8-1529603af139" width="300" />

This isn't exactly a regression since there's a similar issue on npmgraph.js.org currently.   But if we're trying to fix first-load scrolling... well... we should probably actually _fix_ it. :-/

**Comment by broofa** [comment]
Fixed by #232, right?

**Comment by broofa** [comment]
... and now there's arguably a new bug, where deselecting a node (by clicking on the graph background) scrolls you to the top-level node. 🙄  Working on it.

**Comment by fregante** [comment]
> Fixed by #232, right?

Oh I didn't see you had already opened a PR
