### ISSUE TITLE
"View" button issues

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#246]
_Originally posted by @broofa in https://github.com/npmgraph/npmgraph/issues/245#issuecomment-2243339605_

From #239
* [ ] "View" button should probably not be enabled when the current root module is selected (user is already at that view)
* [x] "View" button is not properly aligned
![CleanShot 2024-07-22 at 09 15 13](https://github.com/user-attachments/assets/6ed5ce21-043a-4604-97ce-32ff6e4a7f4c)

**Comment by fregante** [comment]
It's aligned well here (Safari), so it's probably an issue with the text turning into an emoji.

<img width="427" alt="Screenshot 22" src="https://github.com/user-attachments/assets/461c06b2-e220-49e4-8502-23d592a82b1b">

I can use the black triangle to fix it

**Comment by fregante** [comment]
> * "View" button should probably not be enabled when the current root module is selected (user is already at that view)

Agreed, but not related to #239. The link was there before https://npmgraph-git-fork-xhmikosr-xmr-github-npmgraph.vercel.app/?q=express@4.19.2#select=exact%3Aexpress%404.19.2

**Comment by broofa** [comment]
Also, the term "View" feels a bit vague, possibly misleading.  How about "Focus" or "Go To ..."?

**Comment by fregante** [comment]
I think it's hard to explain what the button does exactly. The correct instruction would be something like:

- Create graph starting from this module
- Set as root module
- Start from here

But as you leave words out it starts being less and less effective in explaining what it does. Since we're on the web, links change the page and users can press the back button, so clicking it by mistake has a very low cost.

Single words are also ambiguous:

- Focus: _the module is already focused/selected 🤔_
- Go to: _does it mean scroll to the part of the graph where the module appears?_
- Open: _open what? is it closed now?_

If you don't like "View", we might have two options:

- create a lengthy link label
- set a target/cursor icon and describe it in the `title` attribute

Icon examples: https://www.google.com/search?q=vector+black+white+target+icon

**Comment by broofa** [comment]
How about this ("Go ⤵")...

![CleanShot 2024-07-22 at 14 06 02](https://github.com/user-attachments/assets/d99796c0-da3f-40ee-8b55-311a71de5c76)

The main issue I have with "View" is that it's ubiquitous in the form of the "View" menubar option.  In that context, the expectation is that it has something to do with how the current view is configured, rather than with navigating around the document (which is more what this button is doing.)
