### ISSUE TITLE
Maintainers are miscalculated

### ISSUE THREAD

**Issue by conartist6** [npmgraph/npmgraph#261]
I wish for my packages to no longer display warnings that they have only a single maintainer, but I have no idea where this information is coming from or how it is cached. Obviously the availability of maintainers for a package is not determined at the time that it is published, but rather is a continuously evolving set of circumstances

**Comment by fregante** [comment]
From the UI itself:

> Modules with a single maintainer are at risk of "unplanned abandonment". 

The tool can't determine who is "available", it relies on npm to provide this data. Try running `npm info mem` to get a list of maintainers of the `mem` package for example

**Comment by fregante** [comment]
Specifically, `maintainers` are the npm accounts that "own" a package, as defined by:

https://docs.npmjs.com/cli/v10/commands/npm-owner

**Comment by conartist6** [comment]
That's why I asked about the caching. For example https://npmgraph.js.org/?q=%40bablr%2Fvm shows that the `@bablr/vm` package has a sole maintainer (me). That was true at the time the package was published, but because your tool called me out on this weakness I fixed it by adding a maintainer. While `npm info` reflects the new maintainership the `npmgraph` cache remains stale, telling everyone that they should not use my package as it has (had) poor maintenance coverage.

Here's the npm info output for `@bablr/vm`:

```
@bablr/vm@0.1.16 | MIT | deps: 4 | versions: 17
A VM for executing BABLR grammars
https://github.com/bablr-lang/bablr-vm

dist
.tarball: https://registry.npmjs.org/@bablr/vm/-/vm-0.1.16.tgz
.shasum: 9398676fc326c753593a93b4a54e2081b8e90ef0
.integrity: sha512-EqXnwAB+mRU54atccAFwm9vIa1BOAO/A/ursKvY3ilFzZsg2Nmx1F4POSbR7nOlHIBUXHnIMlIZosXLezSpuEw==
.unpackedSize: 68.5 kB

dependencies:
@bablr/boot-helpers: 0.1.3   @bablr/regex-vm: 0.4.0       @iter-tools/imm-stack: 1.1.0 iter-tools-es: ^7.5.3        

maintainers:
- stirlhoss <stirlhoss@proton.me>
- conartist6 <conrad@burningpotato.com>

dist-tags:
latest: 0.1.16  

published 6 months ago by conartist6 <conrad@burningpotato.com>
```

**Comment by conartist6** [comment]
I've altered the issue to reflect my revised understanding of the problem (based on the information you provided). Could you reopen the issue?

**Comment by fregante** [comment]
This is not a caching issue. I looked into the code and I can't figure out where the maintainers are being lost. The API correctly returns two maintainers for the package.

https://npmgraph.js.org/?q=%40bablr%2Fvm

**Comment by conartist6** [comment]
Interesting. Thanks for opening it up again though, I appreciate it.

**Comment by fregante** [comment]
I think it's because it's reading the array for the specific version, and the API _does_ return only one maintainer there:

```

        },
        "0.1.16": {
            "name": "@bablr/vm",
            "version": "0.1.16",
            "author": {
                "name": "Conrad Buck",
                "email": "conartist6@gmail.com"
            },
            "license": "MIT",
            "_id": "@bablr/vm@0.1.16",
            "maintainers": [
                {
                    "name": "conartist6",
                    "email": "conrad@burningpotato.com"
                }
            ],
```

But I agree that this is not correct, "maintainers" are those who currently have access to the package, not those who had it before.

It's not clear to why this field appears here though. In a package I started managing around v5, I already appear as a maintainer in v1.1.0 and the API response does not have that `maintainer` field for every version.

https://npmgraph.js.org/?q=mem%401

**Comment by fregante** [comment]
### Other bug on https://npmgraph.js.org/?q=webext-storage-cache

<img width="135" alt="Screenshot" src="https://github.com/user-attachments/assets/b517a8e4-505a-4348-88d5-11dbdc725823">
