### ISSUE TITLE
Logotype

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#276]
The site is a bit forgettable, it doesn't have a name anywhere, compare this to other tools like: https://bundlephobia.com/package/webext-tools@2.0.1

I think we can have a small logotype (logo made of text)  to show somewhere above the search field, similar to Node.js' and npm's

I didn't find either one of those fonts, but I was thinking we could use another blocky font like them. There are [many on dafont](https://www.dafont.com/theme.php?cat=301&page=1&psize=xs&text=npmgraph) but most of them are pretty bad, especially at small sizes.

Examples:

- <img src="https://github.com/user-attachments/assets/5bc7a848-db69-4dea-98df-453b861761ce" width="170"> [link](https://www.dafont.com/tt-octosquares.font?text=npmgraph&psize=s)
- <img src="https://github.com/user-attachments/assets/c321f6a7-4932-4222-b71c-2faf243cdabc" width="170">  [link](https://www.dafont.com/robot-2.font?text=npmgraph)
- <img src="https://github.com/user-attachments/assets/a35f8eb5-e740-4eba-a299-aa21db85695b" width="170">  [link](https://www.dafont.com/tt-mussels.font?text=npmgraph&fpp=200&psize=s) 
- <img src="https://github.com/user-attachments/assets/d2610215-6507-4e24-bb05-7488bfe9bc40" width="170">  [link](https://www.dafont.com/classic-robot.font?fpp=200&psize=s&text=npmgraph)

But there are many better. This issue is to explore the idea

Related:

- https://github.com/npmgraph/npmgraph/issues/277

**Comment by fregante** [comment]
Also related, this PR will add a mention of "npmgraph" in the Start tab, and we could eventually replace that text with the logo maybe?

- https://github.com/npmgraph/npmgraph/pull/258

<img width="426" alt="352803533-b9171991-bcee-4f70-8d26-e2e52449c987" src="https://github.com/user-attachments/assets/c23c3d2c-2324-4097-809e-4e223c44c40f">

**Comment by fregante** [comment]
I generated this via some random AI site, it would look nice on the homepage but not so much in the sidebar, unless we flatten the whole site. The color isn't too bad either.

<img width="200" alt="Screenshot 15" src="https://github.com/user-attachments/assets/c8d2e05b-7698-46d3-8fa1-76577012c54b">


```svg
<svg color-interpolation-filters="sRGB" viewBox="0 0 340 250" xmlns="http://www.w3.org/2000/svg"><path d="m47.51 144.915v-49.83h234.98" fill="none" stroke="#f66048" stroke-opacity=".5" stroke-width="20"/><g transform="translate(47.51 95.085)"><path d="m0 0h244.98v59.83h-244.98z" fill="#f66048"/><path d="m33.59 49.83v-39.83h-7.54v19.51l-8.6-19.51h-7.45v39.83h7.55v-19.56l8.65 19.56zm12.58-14.89h9.96l6.23-6.28v-12.43l-6.23-6.23h-17.51v39.83h7.55zm0-17.4h6.49l2.21 2.11v5.59l-2.21 2.16h-6.49zm44.81 32.29v-39.83h-7.54l-4.28 12.52-4.22-12.52h-7.55v39.83h7.55v-16.3l4.22 12.53 4.28-12.53v16.3zm28.82-27.26v-6.34l-6.24-6.23h-11.26l-6.29 6.23v27.36l6.29 6.24h11.26l6.24-6.24v-14.33h-12.78v7.54h5.23v3.32l-2.16 2.17h-4.32l-2.17-2.17v-20.42l2.17-2.16h4.32l2.16 2.16v2.87zm12.57 11.12h3.12l4.48 16.14h7.84l-4.72-16.95 5.53-5.48v-11.17l-6.29-6.23h-17.5v39.83h7.54zm0-16.15h6.49l2.21 2.11v4.28l-2.21 2.21h-6.49zm37.32 32.29h7.75l-7.9-39.83h-8l-7.89 39.83h7.64l.56-2.77h7.34zm-2.01-10.26h-4.33l2.17-10.91zm22.33-4.63h9.96l6.24-6.28v-12.43l-6.24-6.23h-17.5v39.83h7.54zm0-17.4h6.49l2.21 2.11v5.59l-2.21 2.16h-6.49zm44.97 32.29v-39.83h-7.5v16.14h-8.7v-16.14h-7.54v39.83h7.54v-16.14h8.7v16.14z" fill="#f9e8de"/></g></svg>
```

**Comment by broofa** [comment]
Let's go with [the Orbitron font](https://fonts.google.com/specimen/Orbitron?preview.text=npmgraph&classification=Display&stroke=Sans+Serif).

It's a nice, clean design that's nearly identical to the "Classic Robot" font you suggest, above.  And it's a Google Web Font, which has a bunch of advantages.

**Comment by fregante** [comment]
Yeah the classic robot was my favorite so far because it kept some curves (which we have on the lines)

Now I just have to figure out how to turn that into an SVG `path` using web tools 😂 (I don't have any design authoring tools installed at this moment)

**Comment by broofa** [comment]
> I don't have any design authoring tools installed at this moment

[Inkscape](https://inkscape.org/)?  It's my goto vector art editor.  It uses SVG as it's native document format, so tends to do SVG stuff really well.  For example ...
* Create a new document
* Create the text using font of choice
* Select text
* Object -> Object to Path
* File -> Document Properties -> Resize to Content
* File -> Export -> (select "Plain SVG" output format) 

Voila...
![npmgraph](https://github.com/user-attachments/assets/5ee5f04a-9d25-4719-96a8-c703fda97f12)

**Comment by fregante** [comment]
Or… https://danmarshall.github.io/google-font-to-svg-path/

Thanks though 😁 

 I'm almost done

**Comment by fregante** [comment]
c-c-c-check
