### ISSUE TITLE
Add homepage

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#277]
For example:

<img width="685" alt="Screenshot" src="https://github.com/user-attachments/assets/1530e51b-f718-4377-9da0-94308d35cc6a">

Since npmgraph is a SPA, it wouldn't be too complicated to create something like that using the contents of the Start tab + a larger logo.

Related:

- https://github.com/npmgraph/npmgraph/issues/276

**Comment by broofa** [comment]
100% agree.  The current first-time user experience is a suboptimal.

**Comment by fregante** [comment]
Random mockup: _just show the start panel_

This, plus links to the repo and sponsorships, would keep the style of the tool front and center.


I'm kind of slowly iterating on npmgraph, but it might be good to review the UI as a whole at some point. It might be good to get some UI designer on board.

<img width="817" alt="Screenshot 9" src="https://github.com/user-attachments/assets/d96bd001-a093-4409-9708-fc4a48c04ebb">
