### ISSUE TITLE
Great tool, missing one thing -> select/search dependency bij name

### ISSUE THREAD

**Issue by ronaldhoek** [npmgraph/npmgraph#281]
First I would like to mention that I'm amazed by this tool - it's very easy to use and gives you exactly the info you need!

However, with large modules/projects the qraph gets so big, it's difficult to find a specific dependency.

So it would be appreciated if a 'search dependency by name' function would be added to the tool. 
Or an (alphabetical) list of modules would be added on which a user could click, to focus the module in the graph.

**Comment by fregante** [comment]
The list is actually in the Graph tab. 

The search/filter is tracked in:

- #222


Until then, you can use ctrl-F to search using your browser feature.

**Comment by ronaldhoek** [comment]
OMG - missed that option completely (click to expand 'all modules' list) - but thanks, this is good enough for me!
