### ISSUE TITLE
Add button to reset exclusions

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#282]
Say you're on https://npmgraph.js.org/?q=ghub#collapse=express%2Chubdown&select=exact%3Ahubdown%402.6.0

The only way to reset the exclusions is to shift-click on each one again.

I'd suggest to:

- [ ] Show an additional list of excluded modules in the Graph > Modules section 
- [ ] Add a "clear" button near that list (i.e. go to `https://npmgraph.js.org/?q=ghub`)

Similar to:

- https://github.com/npmgraph/npmgraph/issues/257

**Comment by broofa** [comment]
There's an "Expand All" button on the Graph pane already ...
![CleanShot 2024-08-09 at 10 04 45](https://github.com/user-attachments/assets/6a311e86-dc02-46a1-bc62-b879b7a49c2e)

**Comment by fregante** [comment]
Great! That's good enough for me
