### ISSUE TITLE
Support cmd+enter to search in new tab

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#296]
1. Open https://npmgraph.js.org/?q=firefox-profile-js%404.6.0
2. Type "xo"
3. Press cmd+enter

The search should open in a new tab. This is supported in native forms, for example here on GitHub's issue search

**Comment by broofa** [comment]
'Not sure I understand.

**Comment by broofa** [comment]
I'm not sure I follow.  On github, the search bar (top of this page) gets focus when you type "/", and npmgraph already mimics that.  And cmd+enter doesn't do anything when focus is in the search bar here (not for me, anyways, on Chrome+Mac).

The only thing "cmd+enter" does here on GH is act as a shortcut for the "Comment" button when focus is in the "Add a comment" field... but that's not a search-related action.  At no point does it open a new browser tab.

**Comment by fregante** [comment]
Disregard the GitHub comment, they break it in some places. It works in others.

See it working on native HTML forms:

![form](https://github.com/user-attachments/assets/7d722d2c-c588-4dc4-861a-0949ee900789)

**Comment by fregante** [comment]
Oh, you know what. I think this is a Safari-only behavior 😨

**Comment by fregante** [comment]
Chrome supports cmd+clicks on `submit` buttons, but not cmd+enter:

![form](https://github.com/user-attachments/assets/cbaa465e-b36d-410d-9915-1ff072e64639)
