### ISSUE TITLE
Expose search format for automatic browser detection (open search)

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#301]
npms.io uses this tag to tell browsers how to format search queries:

```html
<link title="npms.io" type="application/opensearchdescription+xml" href="https://npms.io/opensearch.xml" rel="search">
```

In short, after visiting npmgraph.js.org for the first time, the browser will remember how to search on it, so the user can type `npmg<Tab>react<Enter>` and land on https://npmgraph.js.org/?q=react

**Comment by broofa** [comment]
Does this actually work?

'Pretty sure [OpenSearch doesn't work on Chrome](https://x.com/googlechrome/status/1504858912692084745).  And support in other browsers "[varies](https://github.com/Fyrd/caniuse/issues/5650)".

E.g. [IMDB.com](https://www.imdb.com/) seems to be OpenSearch enabled, but I don't see Firefox or Safari doing anything interesting with that information.  (E.g. typing "imdb[TAB]" in the search bar doesn't do anything in either browser.)

**Comment by fregante** [comment]
It seems that Firefox requires extensions add search engines: https://addons.mozilla.org/en-US/firefox/extensions/category/search-tools/

<img width="691" alt="Screenshot 10" src="https://github.com/user-attachments/assets/1aade431-c0e7-49f9-a650-ddd1eb1e7bb6">

I can potentially look into it, it's probably a handful of lines that we never have to change again. Same for this setup, even if it's (apparently) Safari-only.

**Comment by fregante** [comment]
Uh? Chrome supports it too, I didn't do anything. It's kinda hard to reach (it appears _maybe_ after the search suggestions) but this just confirms that it's still broadly supported and we can add it too:

<img width="453" alt="Screenshot" src="https://github.com/user-attachments/assets/a4bb49df-3175-4c9e-a579-d027f2c9e839">

**Comment by fregante** [comment]
Yeah they're still loaded, but not immediately active and prominent as before:

```
chrome://settings/searchEngines?search=Inactive+shortcuts
```

<img width="685" alt="Screenshot" src="https://github.com/user-attachments/assets/69f6341e-adbf-43dc-a093-03ab89b75c22">

**Comment by broofa** [comment]
Okay, _technically_ it works, but the manual actions needed to set it up are unintuitive and obscure enough I'm skeptical many people will find it.  Meanwhile typing "np"+ENTER is all that's needed to get to the npmgraph search field.

If you want to merge a PR for this, though, I won't object.  It's just not something I see myself or many other people using.  🤷

https://github.com/user-attachments/assets/01d5e477-171e-4b08-9bc2-5f856363f4f0

**Comment by fregante** [comment]
> Meanwhile typing "np"+ENTER is all that's needed to get to the npmgraph search field.

That's not a guarantee. This is what happens in both Chrome and Safari for me.

![form](https://github.com/user-attachments/assets/848d21a6-777b-46fb-a03b-f61c4112cb24)



> the manual actions needed to set it up are unintuitive and obscure enough

Why are we arguing about this? 😅 Those who do see it and use it will welcome it. It's 5 lines of code I can copy-paste and never look at again.

**Comment by broofa** [comment]
> Why are we arguing about this?

We're not.  I went belly up in my last comment... I just needed lodge my very-weak objections first.  😆

**Comment by fregante** [comment]
> > Why are we arguing about this?
> 
> We're not.

[Yes we are.](https://www.youtube.com/watch?v=ohDB5gbtaEQ)
