### ISSUE TITLE
Clicking on a module in the sidebar only scrolls to the bottom (Firefox, Safari)

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#37]
![](https://user-images.githubusercontent.com/1402241/103596316-40f02000-4ec3-11eb-90d6-1bdbf8ece4ea.gif)

0. Open Firefox or Safari
1. Visit http://npm.broofa.com/?q=webpack
2. Click any sidebar module link
3. Notice that the module is focused but the graph is always only scrolled to the bottom

It works correctly only in Chrome

**Comment by broofa** [comment]
Hmm, good catch.  So... yeah, `scrollIntoView()` has long been problematic for SVG elements.  Chrome only recently (w/in the last 1-2 years?) fixed this issue.  I guess Safari and Firefox still need to figure it out.

If there's a simple solution to this I'd be willing to take a PR, but converting between SVG coordinate spaces and HTML-DOM space is probably non-trivial.  Not something I have time for at the moment.

**Comment by fregante** [comment]
It looks like `getBoundingClientRect` returns the correct coordinates in Safari, regardless of the zoom. Calculating the required scroll distance is probably trivial, something like

```js
const moduleRect = module.getBoundingClientRect();
const graphRect = graph.getBoundingClientRect();
const xDiff = (graphRect.width / 2) - moduleRect.x;
const yDiff = (graphRect.height / 2) - moduleRect.y;
graph.scrollBy(xDiff, yDiff); // Always tries to keep it centered
```
