### ISSUE TITLE
Hiding a dependency and all of its subs from the graph

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#39]
The opposite of https://github.com/broofa/npmgraph/issues/38, some dependencies are noisy and it'd be best to exclude them from the tree.

From https://github.com/broofa/npmgraph/issues/35#issuecomment-753477670:

> This is a good idea, but is non-trivial to implement. Please create issue and elaborate a bit more on how you'd like this to work. Specific questions:
> 
> * Would hiding a module subtree cause graph to re-render, or just leave blank space in the existing graph?  (Asking because re-rendering large graphs is an expensive _and blocking_ operation, so risks making for a very sluggish, unresponsive UI)

I think that `parcel-bundler` would leave quite large holes in the graphs, so while that'd be a fast operation, I'm not sure that it'd be the best way to display it

> * Is hiding a module a persistent action?  I.e. does it stay hidden in any subsequent graphs the user might go to?

I don't think anything else is persistent so why would this be any different?

> * What does a hidden module look like in the graph?  In the inspector?

The hidden module’s **sub-dependencies** would disappear from both, it would just display the sole module as if it had 0 dependencies. It would appear in both, marked as "hidden" somehow.

> * ... and how might you unhide a module?

Hiding/unhiding would probably have to happen with a checkbox next to each dependency in the inspector, or as a select/dropdown where you can pick which packages to hide.

**Comment by Krinkle** [comment]
👍 I like this idea! Seeing the total size of the graph and being able to zoom and pan through it, as-is, is for me the main value and reason for using this tool. However, I do agree that it would be quite helpful to be able to more easily navigate the graph piecemeal. Right now, if a module has many indirect dependencies, then the direct depencies may be visually far apart, thus leading to a viewer desire to narrow down what is included in the graph.

I wonder though if we could visually prioritise the direct dependencies, without neccecarily hiding the rest of the graph. This could perhaps happen by default when inside the focussed mode of https://github.com/broofa/npmgraph/issues/38, or if it is smooth enough, perhaps even all the time?

Perhaps something like Avanka's [npmgraph](https://github.com/anvaka/npmgraph.an):
| [npm.avanka.com](https://npm.anvaka.com/#/view/2d/eslint/7.0.0) | –
|--|--
| <img width="971" alt="avanka-1" src="https://user-images.githubusercontent.com/156867/103600417-3f444d80-4eff-11eb-9a4b-9ee40031bcea.png"> | <img width="944" alt="avanka-2" src="https://user-images.githubusercontent.com/156867/103600418-3fdce400-4eff-11eb-88ab-55fe9bcee08d.png"> | 

This isn't the most user-friendly to navigate, however. Perhaps there are better ways of visually "prioritising" (drawing direct links closer to the selected node, in a more prominent size or color) within a large graph.

Or maybe it's better to have an entirely separate mode as suggested by @fregante in this issue. That mode would perhaps be more akin to Snyk's dependency browser:

| [Snyk](https://snyk.io/test/npm/qunit/2.13.0?tab=dependencies)
|--
| <img width="484" alt="snyk-dependencies" src="https://user-images.githubusercontent.com/156867/103600427-453a2e80-4eff-11eb-9f98-b5ccf1c372b4.png">

**Comment by fregante** [comment]
I think you're talking almost entirely about #38, which is the opposite of this issue. 

This issue is about hiding dependencies that have huge graphs so that I can explore the rest of the packages without noise (initially shown in #35)

**Comment by broofa** [comment]
> I don't think anything else is persistent so why would this be any different?

If, as I suspect, hiding subgraphs is going to be expensive then requiring users to hide subgraphs they're not interested in each and every time a new graph is rendered will be painful.  Remembering which subgraphs a user is not interested in avoids that.  It also makes subsequent graph rendering faster and more efficient.  I.e. I suspect it provides a better overall experience.

> I wonder though if we could visually prioritise the direct dependencies

I'm not sure this really solves the problem.  For **really** large graphs, the excess information is effectively hidden already. Module names end up so small as to be indistinguishable.  That Anvaka example is solving a problem (overlapping names) that this tool doesn't really have.

Ideally users could click on a module in the graph to expand and collapse it's dependencies, as you would in a classic tree view.  (I've actually toyed with the idea of providing a tree view ala Snyk or `npm ls`, but these aren't acyclic graphs so tree views are a bit awkward for users to work with.)

The problem is that efficient graph layout updates aren't supported by the [layout library I'm using](https://github.com/hpcc-systems/hpcc-js-wasm).  And, while there are other layout libraries out there that support incremental updates, none of them do anywhere near as good a job at actual layout.  Thus, I'm loathe to switch to a different solution at this time.

**Comment by fregante** [comment]
> every time a new graph is rendered

How often does that happen? My understanding is that it's rendered once per session (i.e. package.json drop or module search). The suggested feature would _also_ render it when the user hides a module, which the user would expect.

> * Is hiding a module a persistent action?  I.e. does it stay hidden in any subsequent graphs the user might go to?

Maybe I don't understand your question. How _persistent_ are we talking? The only persistency I'd expect is:

1. Hide `parcel-bundler`
2. Graph is updated
3. Hide `web-ext`
4. Graph is updated with **both** dependencies hidden

That's all. If I reload the page I don't expect them to still be hidden.

I think this kind of depends on how you see the app: I see it as stateless, anything that's not in the URL shouldn't be preserved in the next load IMHO.

> click on a module in the graph to expand and collapse it's dependencies

That's what this issue is about, with only the performance being an issue.

What about this compromise **if it's a large tree**: (this can be determined by measuring how long the first layout took)

- Hiding a package will only hide the dependencies, this is instant
- Offer a "update tree" button to re-layout

**Comment by fregante** [comment]
This was done in https://github.com/npmgraph/npmgraph/pull/67 💙, although it's not very discoverable

![s](https://github.com/npmgraph/npmgraph/assets/1402241/bb7ac80f-bae8-4693-b862-dd1181973cb9)
