### ISSUE TITLE
Setup Vercel builds

### ISSUE THREAD

**Issue by broofa** [npmgraph/npmgraph#62]
'Took a quick look at setting this up in Vercel.  Unfortunately they don't allow organization-owned repos on personal accounts so I don't think we can do this on a free plan.  But they do [support opensource projects](https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project).

If you could take care of setting that up, that would be helpful.

Since we're going this route, It probably makes sense to have building  the `docs/` dir be a required part of making commits.  `uuid` does something like this.  The CI workflow builds the docs and fails if it results in any changed files.

**Comment by fregante** [comment]
> **Sponsorship Criteria**
> A Vercel banner in the footer of each site page.

I think it'd be rather tacky and take up screen real estate given that the footer here is fixed

**Comment by fregante** [comment]
Netlify works! It's a static site after all. https://npmgraph.netlify.app
If you register and give me your email I can add you to the "team"

Next steps:

1. Change Netlify setting to the .js.org URL
2. Send a PR to the js.org repo to update the CNAME
3. Drop any remnants of GitHub pages, including the "docs" folder name and the CNAME file

**Comment by fregante** [comment]
> The CI workflow builds the docs and fails if it results in any changed files.

I don't get this part. Why would it fail if files are changed?

**Comment by fregante** [comment]
For the record, Netlify also automatically builds PRs on their own URLs.

**Comment by broofa** [comment]
> I think it'd be rather tacky

Agreed.  That's where I stopped reading as well. 😕 

> give me your email I can add you to the "team

`robert@broofa.com`

> and take up screen real estate given that the footer here is fixed.

FWIW, I'm open to revisiting the UI, including the footer (but that's a different topic.)

>

**Comment by rauchg** [comment]
Sorry we disappointed y'all here. We sponsor a bunch of Open Source projects that take up _**quite significant**_ bandwidth and function invocation resources, so we added this constraint as a way to balance things out.

If you still want to consider Vercel, we're always happy to make exceptions when that requirement doesn't make sense, which seems like the case here (I can see how it awkwardly gets in the way of the application's UI).

**Comment by fregante** [comment]
Thanks Guillermo for vercel and for the explanation. How did you even find this issue? 😂 Anyway it’s understandable, it’s a free tier so it’s bound to have limits. For now I’ll try Netlify and if that doesn’t work out I’ll take your offer 😁

**Comment by fregante** [comment]
Well it looks like we'll have to take your offer, Guillermo! 😁 

> <img width="300" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/115108534-34d42e00-9f9b-11eb-92e3-0ab3b6594f63.png">


The project is already set up on npmgraph.vercel.app

**Comment by broofa** [comment]
> ...we'll <strike>have to</strike> **get to** take your offer ...

😉 

@rauchg: If you could hook us up that would be awesome!  I'm 'broofa' on Vercel (just joined).  I assume @fregante  is using his username there as well.  I'm also curious how you caught wind of this issue.  Either way, thank you.

BTW, I see @jordwalke is one of your investors.  He and I used to work together at Facebook.  (Hi, Jordan!)  Funny how small this world is.

**Comment by broofa** [comment]
FYI, 'just emailed Vercel support asking for them to set us up.

**Comment by broofa** [comment]
From Vercel support:

> I can see that you have deployed https://npmgraph.vercel.app/ to a personal account. Would it be possible to deploy this to a Vercel Pro (team) plan on a trial and share with us your team slug? This way we'll make sure the sponsorship is applied before your trial period runs out.

@fregante I've forwarded you the full email.. Can you take care of setting up that team account and responding to them?  (If you'd rather I do it, let me know.)

**Comment by fregante** [comment]
All done. https://npmgraph.vercel.app points to this repo and will be automatically deployed.

Can you send another PR to js.org to update the CNAME?

cname.vercel-dns.com or 76.76.21.21

**Comment by fregante** [comment]
Once the domain is set up, I'll drop the current GitHub Pages configuration and leave it as clean as possible

**Comment by broofa** [comment]
https://github.com/js-org/js.org/pull/5833

**Comment by fregante** [comment]
I'm cleaning up the build now

**Comment by fregante** [comment]
Future reference: I cleaned up the old deployments

Before: 

<img width="215" alt="Screenshot 5" src="https://github.com/npmgraph/npmgraph/assets/1402241/513ee74b-4e94-40a1-8da6-07be344f9a8b">


After:


<img width="196" alt="Screenshot 6" src="https://github.com/npmgraph/npmgraph/assets/1402241/5a737baa-1bac-492d-93c3-8cb8e73a8127">

Using this command by ChatGPT:

```sh
gh api 'repos/npmgraph/npmgraph/deployments?page=1&environment=github-pages' -X GET -H "Accept: application/vnd.github.ant-man-preview+json" \
        | jq '.[] | select(.environment == "github-pages") | .id' \
        | xargs -I {} sh -c 'gh api repos/npmgraph/npmgraph/deployments/{}/statuses -X POST -F state=inactive && gh api repos/npmgraph/npmgraph/deployments/{} -X DELETE & wait'
```

**Comment by fregante** [comment]
We got an update:

> Hey there,
> 
> Your team npmgraph is currently enrolled in the Vercel sponsorship program.
> 
> Your 100% off discount is expiring on June 14. To give you time to handle this transition, we will automatically enroll your team into a $300/mo discount for the next 6 months, starting on June 14 and ending on December 14.
> 
> Thank you for partnering together with us.
> 
> Please reach out to sponsorships@vercel.com if you have any questions.
> 
> ▲ Vercel

**Comment by broofa** [comment]
Thanks for letting me know.  Maybe time for me to move `npmgraph` to my personal account?

Looking at usage #'s, it seems like it'll work just fine with the hobby account I have.
