### ISSUE TITLE
Feature: New UI(?)

### ISSUE THREAD

**Issue by broofa** [npmgraph/npmgraph#65]
There's a few things about the current UI that bother me.
* As mentioned in #62, there's no good location for <strike>NASCAR stickers</strike> sponsor information
* The "ⓘ" (info) tab was supposed to be for that sort of thing, as well as copyright and license info, but is really just the upload-a-package.json tab now, (making the "ⓘ" symbol misleading 😢  )
* We jump through a lot of hoops with the inspector - auto-showing it, auto-switching tabs - that could be avoided if we used modal dialogs for that information.

I'm wondering if we couldn't just get rid of the inspector altogether and, instead ...

* [Home screen](https://wireframe.cc/xJCXkw) (no graph)
* [Graph screen](https://wireframe.cc/OtCSuE)
* [Detail screen](https://wireframe.cc/1ugx4r) (for graph, module, or graph settings)

**Comment by fregante** [comment]
I’m not particularly bothered by the current setup. Maybe I’d just rework the tabs somehow (merge, split) but other than that we can still include the sponsor logo in the info page without having to show a logo all the time, especially since we already got the exception. 🙏
