### ISSUE TITLE
Feature: Module selection should highlight whole dependency tree, and call out any dependencies unique to the selected module. 

### ISSUE THREAD

**Issue by broofa** [npmgraph/npmgraph#72]
One question I often have about a dependency graph is, "If I add/remove [module X], what dependencies _actually_ get added / removed from the graph."  I don't know of any tools that answer this particularly well, but I think we're well positioned to do so.

For example, we could enhance the current module selection to highlight the whole descendent dependency tree, rather than just immediate child dependencies.  And, further highlight which of those dependencies are exclusive to the selected module. (i.e. which ones would actually get removed if the selected module is removed.)

#67 sort of does this in that when you collapse a module, any dependencies it shares with other modules will remain in the graph - but it's hard to see due to how the graph gets re-laid out.

**Comment by fregante** [comment]
I think questions like this are difficult to show in a graph, generally speaking.

In this case specifically I think it would make the most sense to show an additional, separate graph for the new module and its dependencies, dimming any dependencies that overlap with the existing ones.
