### ISSUE TITLE
Feature: Hope that the settings can be persisted

### ISSUE THREAD

**Issue by wenmin92** [npmgraph/npmgraph#77]
Currently, the settings are not preserved, and they must be reset the next time opened, which is a bit annoying. I think it will be more intuitive if the settings can be persisted.

**Comment by broofa** [comment]
Settings are now persisted in the URL hash (see #151 ).  This is a bit different than persisting in storage, but allows for sharing of view settings as part of URL, and also allows settings to play nicely with the browser history.

I'm pretty happy with how this "feels", so I'm going to close this out.
