### ISSUE TITLE
Deprecated modules not shown when colorized

### ISSUE THREAD

**Issue by broofa** [npmgraph/npmgraph#81]
Deprecated+Colorized modules should have some sort of diagonal striping like their uncolorized counterparts.  Currently they don't ...

Uncolorized: ![image](https://user-images.githubusercontent.com/164050/119735626-51744900-be18-11eb-84d2-4529523d7ca3.png)

Colorized: ![image](https://user-images.githubusercontent.com/164050/119735650-5c2ede00-be18-11eb-9f98-825a630bf51e.png)

**Comment by fregante** [comment]
I think the only solution to this would be to add a second `path` to overlay the base one.

Alternatively we can move the style to the border

**Comment by broofa** [comment]
Closing.  'Not worth worrying about.
