### ISSUE TITLE
Add a place for sponsor links

### ISSUE THREAD

**Issue by broofa** [npmgraph/npmgraph#88]
We're on Vercel's opensource plan.  I'd like to get us on an opensource plan for bugsnag.  Both companies ask for a sponsorship logo, so we should create a place for putting this sort of thing.  Maybe on the "ⓘ" tab...?

And while we're at it we should add a "Sponsor NPMGraph Contributors" section of some sort.

**Comment by fregante** [comment]
> We're on Vercel's opensource plan

Not anymore
