### ISSUE TITLE
paste in package

### ISSUE THREAD

**Issue by jimmywarting** [npmgraph/npmgraph#97]
I work with private packages that are not hosted on npm...
so it would make life easier if it where just possible to copy paste in the raw content of the package.json (or the file itself) and paste it in anywhere onto the site

**Comment by fregante** [comment]
Example UI from https://www.remove.bg

<img width="420" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/139539138-83983640-392e-48ef-b51c-f8fd99b5b427.png">

**Comment by jimmywarting** [comment]
as long as the windows has focus then it's okey to use it. (`window.onpaste`) otherwise a thing like clipboard access and reading it from clipboard on a click event could work too <b>Read json package from <ins>clipboard</ins></b>

**Comment by broofa** [comment]
Just a quick note to add that being able to work with yarn.lock files would be nice as well

**Comment by broofa** [comment]
Just noting that this should be straight-forward to implement now that we have [the `packages` hash param](https://github.com/npmgraph/npmgraph/#packages-hash-param-json-encoded).
