### ISSUE TITLE
npmgraph does not support npm dependency aliases

### ISSUE THREAD

**Issue by peternhale** [npmgraph/npmgraph#99]
npm v 6.9.0 added the ability for one to alias a npm module with

`npm install got-11.8.2@npm:got@11.8.2`

This stored as in package.json

`"got-11.8.2": "npm:got@^11.8.2"`

When npmgraph loads the package.json the dependency graph node is displayed with a grey background and the side bar shows the error below when the module is selected.

```
got-11.8.2
Information and dependencies for this module cannot be displayed due to the following error:

HTTP Error 404
```

**Comment by broofa** [comment]
Fixed.
